docs/guides/latest/backends/azure.md
docs/guides/latest/backends/b2.md
docs/guides/latest/backends/gcs.md
docs/guides/latest/backends/local.md
docs/guides/latest/backends/rest.md
docs/guides/latest/backends/s3.md
docs/guides/latest/backends/swift.md
docs/guides/v1alpha1/backup.md
docs/guides/v1alpha1/monitoring/builtin.md
docs/guides/v1alpha1/monitoring/coreos.md
docs/guides/v1alpha1/monitoring/grafana.md
docs/guides/v1alpha1/monitoring/overview.md
docs/guides/v1alpha1/offline_backup.md
docs/guides/v1alpha1/platforms/aks.md
docs/guides/v1alpha1/platforms/eks.md
docs/guides/v1alpha1/platforms/gke.md
docs/guides/v1alpha1/platforms/minio.md
docs/guides/v1alpha1/platforms/rook.md
docs/setup/install.md
docs/setup/uninstall.md

Use simpler /raw/ urls for documents

---

docs/concepts/crds/backupconfiguration_template.md
docs/examples/workloads/backup_template.yaml

xref: https://github.com/stashed/stash/issues/792

Add TARGET_RESOURCE variable for BackupConfigurationTemplate

---

docs/design.md
docs/guides/backup_restore_pvc.md
docs/guides/latest/advance-use-case/clone-pvc.md
docs/guides/latest/advance-use-case/instant-backup.md
docs/guides/latest/auto-backup/pvc.md
docs/guides/latest/auto-backup/workload.md
docs/guides/latest/ownership.md
docs/guides/latest/volumes/pvc.md
docs/guides/latest/volumesnapshot/deployment.md
docs/guides/latest/volumesnapshot/pvc.md
docs/guides/latest/volumesnapshot/statefulset.md
docs/guides/latest/workloads/daemonset.md
docs/guides/latest/workloads/deployment.md
docs/guides/latest/workloads/statefulset.md
docs/guides/v1alpha1/platforms/eks.md
docs/guides/v1alpha1/platforms/minio.md
docs/guides/v1alpha1/restore.md

Use `we are going to` instead of `we will`

---

docs/concepts/crds/snapshot.md

I think you meant `status.paths` instead of `status.path`

Fixed snapshot documentation status.paths

---

docs/guides/latest/advanced-use-case/clone-pvc.md
docs/guides/latest/advanced-use-case/instant-backup.md
docs/guides/latest/advanced-use-case/pause-backup.md
docs/guides/latest/auto-backup/database.md
docs/guides/latest/auto-backup/pvc.md
docs/guides/latest/databases/overview.md
docs/guides/latest/platforms/aks.md
docs/guides/latest/platforms/eks.md
docs/guides/latest/platforms/gke.md
docs/guides/latest/platforms/minio.md
docs/guides/latest/platforms/rook.md
docs/guides/latest/volumes/pvc.md
docs/guides/latest/volumesnapshot/deployment.md
docs/guides/latest/volumesnapshot/overview.md
docs/guides/latest/volumesnapshot/pvc.md
docs/guides/latest/volumesnapshot/statefulset.md
docs/guides/latest/workloads/daemonset.md
docs/guides/latest/workloads/deployment.md
docs/guides/latest/workloads/statefulset.md

Always use URLs relative to git repository

---

docs/guides/latest/advanced-use-case/clone-pvc.md
docs/guides/latest/advanced-use-case/instant-backup.md
docs/guides/latest/advanced-use-case/pause-backup.md
docs/guides/latest/auto-backup/database.md
docs/guides/latest/auto-backup/pvc.md
docs/guides/latest/auto-backup/workload.md
docs/guides/latest/backends/gcs.md
docs/guides/latest/platforms/gke.md
docs/guides/latest/volumes/pvc.md
docs/guides/latest/workloads/daemonset.md
docs/guides/latest/workloads/deployment.md
docs/guides/latest/workloads/statefulset.md

xref: https://github.com/stashed/stash/issues/840

Clarify that GCS backend needs Storage Object Admin role

---

docs/guides/latest/cli/_index.md
docs/guides/latest/cli/cli.md
docs/guides/latest/cli/reference/_index.md

Publish stash cli reference docs

---

docs/CHANGELOG-0.9.md

xref: https://github.com/stashed/stash/issues/935

Write Changelog for release v0.9.0-rc.2 and v0.9.0-rc1

---

.github/workflows/ci.yml

Use forked liche

---

docs/concepts/README.md
docs/concepts/crds/appbinding.md
docs/concepts/crds/backupconfiguration.md
docs/concepts/crds/backupsession.md
docs/concepts/crds/repository.md
docs/concepts/crds/restoresession.md
docs/concepts/crds/snapshot.md
docs/concepts/crds/task.md
docs/examples/workloads/daemonset.yaml
docs/examples/workloads/deployment.yaml
docs/examples/workloads/rc.yaml
docs/examples/workloads/replicaset.yaml
docs/examples/workloads/statefulset.yaml
docs/guides/latest/README.md
docs/guides/latest/auto-backup/database.md
docs/guides/latest/auto-backup/overview.md
docs/guides/latest/auto-backup/workload.md
docs/guides/latest/backends/azure.md
docs/guides/latest/backends/b2.md
docs/guides/latest/backends/gcs.md
docs/guides/latest/backends/local.md
docs/guides/latest/backends/rest.md
docs/guides/latest/backends/s3.md
docs/guides/latest/backends/swift.md
docs/guides/v1alpha1/backends/overview.md
docs/guides/v1alpha1/workloads.md
docs/setup/install.md

Fix broken links

---

docs/setup/install.md

Add Helm 3 installation instructions

---

docs/guides/latest/advanced-use-case/clone-pvc.md
docs/guides/latest/advanced-use-case/instant-backup.md
docs/guides/latest/advanced-use-case/pause-backup.md
docs/guides/latest/auto-backup/database.md
docs/guides/latest/auto-backup/pvc.md
docs/guides/latest/auto-backup/workload.md
docs/guides/latest/monitoring/builtin.md
docs/guides/latest/monitoring/coreos.md
docs/guides/latest/platforms/minio.md
docs/guides/latest/platforms/rook.md
docs/guides/latest/volumes/pvc.md
docs/guides/latest/workloads/daemonset.md
docs/guides/latest/workloads/deployment.md
docs/guides/latest/workloads/statefulset.md
docs/guides/v1alpha1/backup.md
docs/guides/v1alpha1/monitoring/builtin.md
docs/guides/v1alpha1/monitoring/coreos.md
docs/guides/v1alpha1/monitoring/grafana.md
docs/guides/v1alpha1/offline_backup.md
docs/guides/v1alpha1/platforms/minio.md
docs/guides/v1alpha1/platforms/rook.md

Recommend using kind instead of minikube.

---

docs/guides/latest/monitoring/builtin.md
docs/guides/latest/monitoring/coreos.md
docs/guides/latest/monitoring/overview.md
docs/guides/v1alpha1/monitoring/builtin.md
docs/guides/v1alpha1/monitoring/coreos.md
docs/guides/v1alpha1/monitoring/grafana.md
docs/guides/v1alpha1/monitoring/overview.md

Just use Prometheus operator

---

docs/guides/latest/monitoring/builtin.md
docs/guides/latest/monitoring/coreos.md
docs/guides/latest/monitoring/overview.md
docs/guides/v1alpha1/monitoring/builtin.md
docs/guides/v1alpha1/monitoring/coreos.md
docs/guides/v1alpha1/monitoring/overview.md
docs/setup/install.md
docs/setup/uninstall.md

- Make helm 3 recommended method
- Rewrite script to use helm 3

Update installation instructions

---

docs/concepts/crds/function.md

Fixes https://github.com/stashed/stash/issues/972

Fix formatting

---

docs/reference/operator/stash.md
docs/reference/operator/stash_backup-pvc.md
docs/reference/operator/stash_backup.md
docs/reference/operator/stash_check.md
docs/reference/operator/stash_create-backupsession.md
docs/reference/operator/stash_create-vs.md
docs/reference/operator/stash_forget.md
docs/reference/operator/stash_recover.md
docs/reference/operator/stash_restore-pvc.md
docs/reference/operator/stash_restore-vs.md
docs/reference/operator/stash_restore.md
docs/reference/operator/stash_run-backup.md
docs/reference/operator/stash_run-hook.md
docs/reference/operator/stash_run.md
docs/reference/operator/stash_scaledown.md
docs/reference/operator/stash_snapshots.md
docs/reference/operator/stash_version.md
docs/setup/install.md

Update stash operator reference

---

docs/addons/elasticsearch/setup/install.md
docs/addons/elasticsearch/setup/uninstall.md
docs/addons/mongodb/setup/install.md
docs/addons/mongodb/setup/uninstall.md
docs/addons/mysql/setup/install.md
docs/addons/mysql/setup/uninstall.md
docs/addons/postgres/setup/install.md
docs/addons/postgres/setup/uninstall.md

Update Addon Installer

---

docs/guides/latest/monitoring/builtin.md
docs/guides/latest/monitoring/coreos.md
docs/guides/latest/monitoring/overview.md
docs/guides/v1alpha1/monitoring/builtin.md
docs/guides/v1alpha1/monitoring/coreos.md
docs/guides/v1alpha1/monitoring/overview.md
docs/setup/install.md

Use `stash` as the release for helm commands

---

docs/guides/latest/backends/s3.md

Update backend doc to specify how to provide "s3.region"

---

docs/guides/v1alpha1/workloads.md
docs/roadmap.md

Remove outdated roadmap doc

---

.github/workflows/ci.yml
docs/concepts/what-is-stash/architecture.md
docs/guides/latest/auto-backup/database.md
docs/guides/latest/hooks/backup-and-restore-hooks.md
docs/guides/latest/hooks/batch-backup-hooks.md

Use pre-built liche binary

---

docs/reference/cli/_index.md
docs/reference/cli/kubectl-stash.md
docs/reference/cli/kubectl-stash_clone.md
docs/reference/cli/kubectl-stash_clone_pvc.md
docs/reference/cli/kubectl-stash_cp.md
docs/reference/cli/kubectl-stash_cp_backupconfig.md
docs/reference/cli/kubectl-stash_cp_repository.md
docs/reference/cli/kubectl-stash_cp_secret.md
docs/reference/cli/kubectl-stash_cp_volumesnapshot.md
docs/reference/cli/kubectl-stash_create.md
docs/reference/cli/kubectl-stash_create_backupconfig.md
docs/reference/cli/kubectl-stash_create_repository.md
docs/reference/cli/kubectl-stash_create_restoresession.md
docs/reference/cli/kubectl-stash_delete.md
docs/reference/cli/kubectl-stash_delete_snapshot.md
docs/reference/cli/kubectl-stash_download.md
docs/reference/cli/kubectl-stash_trigger.md
docs/reference/cli/kubectl-stash_unlock.md
docs/reference/cli/kubectl-stash_version.md

Update docs for stashed/cli@b913cfc2

---

docs/reference/operator/_index.md
docs/reference/operator/stash.md
docs/reference/operator/stash_backup-pvc.md
docs/reference/operator/stash_backup.md
docs/reference/operator/stash_check.md
docs/reference/operator/stash_create-backupsession.md
docs/reference/operator/stash_create-vs.md
docs/reference/operator/stash_forget.md
docs/reference/operator/stash_recover.md
docs/reference/operator/stash_restore-pvc.md
docs/reference/operator/stash_restore-vs.md
docs/reference/operator/stash_restore.md
docs/reference/operator/stash_run-backup.md
docs/reference/operator/stash_run-hook.md
docs/reference/operator/stash_run.md
docs/reference/operator/stash_scaledown.md
docs/reference/operator/stash_snapshots.md
docs/reference/operator/stash_update-status.md
docs/reference/operator/stash_version.md

Update docs for stashed/stash@9fa95666

---

docs/reference/cli/kubectl-stash_clone.md
docs/reference/cli/kubectl-stash_clone_pvc.md
docs/reference/cli/kubectl-stash_cp.md
docs/reference/cli/kubectl-stash_cp_backupconfig.md
docs/reference/cli/kubectl-stash_cp_repository.md
docs/reference/cli/kubectl-stash_cp_secret.md
docs/reference/cli/kubectl-stash_cp_volumesnapshot.md
docs/reference/cli/kubectl-stash_create.md
docs/reference/cli/kubectl-stash_create_backupconfig.md
docs/reference/cli/kubectl-stash_create_repository.md
docs/reference/cli/kubectl-stash_create_restoresession.md
docs/reference/cli/kubectl-stash_delete.md
docs/reference/cli/kubectl-stash_delete_snapshot.md
docs/reference/cli/kubectl-stash_download.md
docs/reference/cli/kubectl-stash_trigger.md
docs/reference/cli/kubectl-stash_unlock.md
docs/reference/cli/kubectl-stash_version.md

Update docs for stashed/cli@66b3b46c

---

docs/CHANGELOG-v2020.07.08-beta.0.md

Release: v2020.07.08-beta.0
Release-tracker: https://github.com/stashed/CHANGELOG/pull/1

Prepare for release v2020.07.08-beta.0

---

docs/examples/guides/latest/auto-backup/workload/deployment.yaml
docs/guides/latest/auto-backup/database.md
docs/guides/latest/auto-backup/pvc.md
docs/guides/latest/auto-backup/workload.md

Add documentation of `schedule` and `params` auto-backup annotations

---

docs/guides/latest/auto-backup/database.md

Update doc for parameter passing via annotations

---

docs/concepts/crds/backupbatch.md
docs/concepts/crds/restorebatch.md
docs/concepts/crds/snapshot.md
docs/guides/latest/auto-backup/database.md
docs/guides/latest/auto-backup/overview.md
docs/guides/latest/auto-backup/pvc.md
docs/guides/latest/auto-backup/workload.md
docs/guides/latest/backends/local.md
docs/guides/latest/batch-backup/batch-backup.md
docs/guides/latest/batch-backup/overview.md
docs/guides/latest/hooks/batch-backup-hooks.md

Use common warning message for enterprise features

---

docs/reference/cli/kubectl-stash_create_restoresession.md

Update docs for stashed/cli@132ae15d

---

docs/setup/install/community.md
docs/setup/install/enterprise.md

Replace "info.version" of setup guides with respective operator versions

---

docs/setup/install/enterprise.md

Update release name in eterprise installer

---

docs/addons/elasticsearch/README.md
docs/addons/mongodb/README.md
docs/addons/mysql/README.md
docs/addons/percona-xtradb/README.md
docs/addons/postgres/README.md

**We should update these links automatically.**

Fix link in README.md of addons doc

---

docs/addons/elasticsearch/README.md
docs/addons/mongodb/README.md
docs/addons/mysql/README.md
docs/addons/percona-xtradb/README.md
docs/addons/postgres/README.md
docs/guides/latest/addons/overview.md

Use catalogtable & versionlist Hugo shortcode

---

.github/workflows/ci.yml
docs/guides/latest/monitoring/coreos.md
docs/guides/latest/monitoring/overview.md

Fix agent name for monitoring via coreos promtheus operator

---

docs/reference/operator/stash_run.md

Update docs for stashed/stash@58b28e02

---

docs/setup/install/community.md

Clarify Community edition is free to use for commercial purposes

---

docs/setup/upgrade.md

Fixes: https://github.com/stashed/stash/issues/1193

Use single helm command to update the license

---

docs/addons/elasticsearch/README.md
docs/addons/elasticsearch/overview.md
docs/addons/elasticsearch/setup/install.md
docs/addons/elasticsearch/setup/uninstall.md
docs/addons/mongodb/README.md
docs/addons/mongodb/overview.md
docs/addons/mongodb/setup/install.md
docs/addons/mongodb/setup/uninstall.md
docs/addons/mysql/README.md
docs/addons/mysql/overview.md
docs/addons/mysql/setup/install.md
docs/addons/mysql/setup/uninstall.md
docs/addons/percona-xtradb/README.md
docs/addons/percona-xtradb/overview.md
docs/addons/percona-xtradb/setup/install.md
docs/addons/percona-xtradb/setup/uninstall.md
docs/addons/postgres/README.md
docs/addons/postgres/overview.md
docs/addons/postgres/setup/install.md
docs/addons/postgres/setup/uninstall.md

Display Enterprise edition required for database addons

---

docs/reference/cli/kubectl-stash_completion.md

Update docs for stashed/cli@e902dfc8

---

docs/setup/install/community.md

Update Hugo frontmatter param key for installer project

---

docs/setup/README.md
docs/setup/install/kubectl_plugin.md
docs/setup/uninstall/kubectl_plugin.md

Install stash cli using krew

---

docs/CHANGELOG-v2020.10.29.md
docs/guides/latest/auto-backup/database.md
docs/guides/latest/hooks/backup-and-restore-hooks.md
docs/guides/latest/hooks/batch-backup-hooks.md

Release: v2020.10.29
Release-tracker: https://github.com/stashed/CHANGELOG/pull/21

Prepare for release v2020.10.29

---

docs/reference/operator/stash_backup-pvc.md
docs/reference/operator/stash_backup.md
docs/reference/operator/stash_check.md
docs/reference/operator/stash_create-backupsession.md
docs/reference/operator/stash_create-vs.md
docs/reference/operator/stash_forget.md
docs/reference/operator/stash_recover.md
docs/reference/operator/stash_restore-pvc.md
docs/reference/operator/stash_restore-vs.md
docs/reference/operator/stash_restore.md
docs/reference/operator/stash_run-backup.md
docs/reference/operator/stash_run-hook.md
docs/reference/operator/stash_scaledown.md
docs/reference/operator/stash_snapshots.md
docs/reference/operator/stash_update-status.md
docs/reference/operator/stash_version.md

Update docs for stashed/stash@d0a4751b

---

docs/reference/cli/kubectl-stash_clone.md
docs/reference/cli/kubectl-stash_cp.md
docs/reference/cli/kubectl-stash_create.md
docs/reference/cli/kubectl-stash_delete.md
docs/reference/cli/kubectl-stash_version.md

Update docs for stashed/cli@af00ba6c

---

docs/CHANGELOG-v2020.11.17.md

Release: v2020.11.17
Release-tracker: https://github.com/stashed/CHANGELOG/pull/24

Prepare for release v2020.11.17

---

docs/examples/guides/latest/backends/minio.yaml
docs/guides/latest/backends/s3.md

Show scheme in endpoint for Minio Repository

---

docs/setup/install/community.md
docs/setup/install/enterprise.md

Update YAML install instructions

---

docs/guides/latest/monitoring/overview.md
docs/guides/latest/monitoring/prometheus_builtin.md
docs/guides/latest/monitoring/prometheus_operator.md
docs/guides/latest/security/psp.md
docs/guides/v1alpha1/monitoring/builtin.md
docs/guides/v1alpha1/monitoring/coreos.md
docs/guides/v1alpha1/monitoring/overview.md
docs/setup/install/community.md
docs/setup/uninstall/community.md

Rename appscode/stash chart to appscode/stash-community

---

.github/workflows/preview-website.yml

Add preview-website workflow

---

.github/workflows/preview-website.yml
docs/addons/mariadb/_index.md
docs/addons/mongodb/_index.md
docs/addons/mysql/_index.md
docs/addons/percona-xtradb/README.md
docs/addons/percona-xtradb/_index.md
docs/addons/percona-xtradb/overview/index.md
docs/addons/postgres/_index.md
docs/concepts/crds/backupbatch.md
docs/guides/latest/batch-backup/_index.md
docs/guides/latest/batch-backup/batch-backup.md
docs/guides/latest/batch-backup/overview.md
docs/setup/upgrade/index.md

Formatting fix

---

docs/setup/install/community.md
docs/setup/install/enterprise.md

Fix chart home page link

---

docs/setup/upgrade/index.md

Add CRD upgrade instruction in upgrade guide

---

docs/reference/operator/stash.md
docs/reference/operator/stash_backup-pvc.md
docs/reference/operator/stash_backup.md
docs/reference/operator/stash_check.md
docs/reference/operator/stash_create-backupsession.md
docs/reference/operator/stash_create-vs.md
docs/reference/operator/stash_forget.md
docs/reference/operator/stash_recover.md
docs/reference/operator/stash_restore-pvc.md
docs/reference/operator/stash_restore-vs.md
docs/reference/operator/stash_restore.md
docs/reference/operator/stash_run-backup.md
docs/reference/operator/stash_run-hook.md
docs/reference/operator/stash_run.md
docs/reference/operator/stash_scaledown.md
docs/reference/operator/stash_snapshots.md
docs/reference/operator/stash_update-status.md
docs/reference/operator/stash_version.md

Update docs for stashed/stash@f86c22bf

---

docs/reference/cli/kubectl-stash.md
docs/reference/cli/kubectl-stash_clone.md
docs/reference/cli/kubectl-stash_clone_pvc.md
docs/reference/cli/kubectl-stash_completion.md
docs/reference/cli/kubectl-stash_cp.md
docs/reference/cli/kubectl-stash_cp_backupconfig.md
docs/reference/cli/kubectl-stash_cp_repository.md
docs/reference/cli/kubectl-stash_cp_secret.md
docs/reference/cli/kubectl-stash_cp_volumesnapshot.md
docs/reference/cli/kubectl-stash_create.md
docs/reference/cli/kubectl-stash_create_backupconfig.md
docs/reference/cli/kubectl-stash_create_repository.md
docs/reference/cli/kubectl-stash_create_restoresession.md
docs/reference/cli/kubectl-stash_delete.md
docs/reference/cli/kubectl-stash_delete_snapshot.md
docs/reference/cli/kubectl-stash_download.md
docs/reference/cli/kubectl-stash_trigger.md
docs/reference/cli/kubectl-stash_unlock.md
docs/reference/cli/kubectl-stash_version.md

Update docs for stashed/cli@eba049ef

---

docs/guides/latest/monitoring/overview.md
docs/guides/latest/monitoring/prometheus_builtin.md
docs/guides/latest/monitoring/prometheus_operator.md

Update installation commands in monitoring docs

---

.github/workflows/ci.yml
docs/setup/upgrade/index.md

Update catalog crd yaml path

---

docs/setup/install/community.md
docs/setup/install/enterprise.md
docs/setup/uninstall/community.md
docs/setup/uninstall/enterprise.md
docs/setup/upgrade/index.md

- Remove helm 2 instructions
- pre select stash verison in license issuer site

Cleanup docs

---

docs/addons/redis/README.md
docs/addons/redis/helm/index.md
docs/addons/redis/overview/index.md

Fix version not resolving in Redis addon

---

docs/setup/upgrade/index.md

Add generic upgrade instruction for v2021.xx.xx

---

docs/reference/cli/kubectl-stash.md
docs/reference/cli/kubectl-stash_clone.md
docs/reference/cli/kubectl-stash_clone_pvc.md
docs/reference/cli/kubectl-stash_completion.md
docs/reference/cli/kubectl-stash_cp.md
docs/reference/cli/kubectl-stash_cp_backupconfig.md
docs/reference/cli/kubectl-stash_cp_repository.md
docs/reference/cli/kubectl-stash_cp_secret.md
docs/reference/cli/kubectl-stash_cp_volumesnapshot.md
docs/reference/cli/kubectl-stash_create.md
docs/reference/cli/kubectl-stash_create_backupconfig.md
docs/reference/cli/kubectl-stash_create_repository.md
docs/reference/cli/kubectl-stash_create_restoresession.md
docs/reference/cli/kubectl-stash_delete.md
docs/reference/cli/kubectl-stash_delete_snapshot.md
docs/reference/cli/kubectl-stash_download.md
docs/reference/cli/kubectl-stash_trigger.md
docs/reference/cli/kubectl-stash_unlock.md
docs/reference/cli/kubectl-stash_version.md

Update docs for stashed/cli@ed6657aa

---

docs/reference/operator/stash.md
docs/reference/operator/stash_backup-pvc.md
docs/reference/operator/stash_backup.md
docs/reference/operator/stash_check.md
docs/reference/operator/stash_create-backupsession.md
docs/reference/operator/stash_create-vs.md
docs/reference/operator/stash_forget.md
docs/reference/operator/stash_recover.md
docs/reference/operator/stash_restore-pvc.md
docs/reference/operator/stash_restore-vs.md
docs/reference/operator/stash_restore.md
docs/reference/operator/stash_run-backup.md
docs/reference/operator/stash_run-hook.md
docs/reference/operator/stash_run.md
docs/reference/operator/stash_scaledown.md
docs/reference/operator/stash_snapshots.md
docs/reference/operator/stash_update-status.md
docs/reference/operator/stash_version.md

Update docs for stashed/stash@ff417d95

---

docs/addons/elasticsearch/README.md
docs/addons/elasticsearch/overview/index.md
docs/addons/etcd/README.md
docs/addons/etcd/overview/index.md
docs/addons/mariadb/README.md
docs/addons/mariadb/overview/index.md
docs/addons/mongodb/README.md
docs/addons/mongodb/overview/index.md
docs/addons/mysql/README.md
docs/addons/mysql/overview/index.md
docs/addons/nats/README.md
docs/addons/nats/overview/index.md
docs/addons/percona-xtradb/README.md
docs/addons/percona-xtradb/overview/index.md
docs/addons/postgres/README.md
docs/addons/postgres/overview/index.md
docs/addons/redis/README.md
docs/addons/redis/overview/index.md

Fix a few grammatical errors.

---

docs/addons/elasticsearch/auto-backup/index.md
docs/addons/elasticsearch/kubedb/index.md
docs/addons/mariadb/auto-backup/index.md
docs/addons/mariadb/helm/index.md
docs/addons/mongodb/replicaset/index.md
docs/addons/mongodb/sharding/index.md
docs/guides/latest/advanced-use-case/instant-backup.md
docs/guides/latest/advanced-use-case/pause-backup.md
docs/guides/latest/batch-backup/batch-backup.md
docs/guides/latest/hooks/backup-and-restore-hooks.md
docs/guides/latest/hooks/batch-backup-hooks.md
docs/guides/latest/platforms/gke.md
docs/guides/latest/workloads/daemonset.md
docs/guides/latest/workloads/deployment.md
docs/guides/latest/workloads/statefulset.md
docs/guides/v1alpha1/backends/gcs.md
docs/guides/v1alpha1/platforms/gke.md

Fix a typo in some files of the docs.

---

docs/guides/latest/backends/s3.md

Add warning about Minio backend credentials keys

---

docs/setup/upgrade/index.md

Fix upgrade instruction

---

docs/reference/cli/kubectl-stash_create_backupconfig.md
docs/reference/cli/kubectl-stash_create_restoresession.md
docs/reference/cli/kubectl-stash_delete_snapshot.md

Update docs for stashed/cli@34e30bd2

---

docs/reference/operator/stash.md
docs/reference/operator/stash_backup-pvc.md
docs/reference/operator/stash_create-backupsession.md
docs/reference/operator/stash_create-vs.md
docs/reference/operator/stash_forget.md
docs/reference/operator/stash_restore-pvc.md
docs/reference/operator/stash_restore-vs.md
docs/reference/operator/stash_restore.md
docs/reference/operator/stash_run-backup.md
docs/reference/operator/stash_run-hook.md
docs/reference/operator/stash_run.md
docs/reference/operator/stash_snapshots.md
docs/reference/operator/stash_update-status.md
docs/reference/operator/stash_version.md

Update docs for stashed/stash@c81cf41b

---

docs/reference/cli/kubectl-stash_delete_snapshot.md
docs/reference/cli/kubectl-stash_download.md

Update docs for stashed/cli@c90bfcc7

---

docs/reference/operator/stash_update-status.md

Update docs for stashed/stash@eb69ad4e

---

docs/reference/cli/kubectl-stash_pause.md
docs/reference/cli/kubectl-stash_pause_backup.md
docs/reference/cli/kubectl-stash_resume.md
docs/reference/cli/kubectl-stash_resume_backup.md

Update docs for stashed/cli@23631716

---

docs/concepts/crds/backupconfiguration.md
docs/concepts/crds/repository.md
docs/concepts/crds/restoresession.md

Update concept docs for cross-namespace repository.

---

docs/guides/cli/cli.md

Update CLI docs: `downlaod`, `pause`, `resume` & `debug`

---

docs/reference/cli/kubectl-stash.md
docs/reference/cli/kubectl-stash_debug.md
docs/reference/cli/kubectl-stash_debug_backup.md
docs/reference/cli/kubectl-stash_debug_operator.md
docs/reference/cli/kubectl-stash_debug_restore.md
docs/reference/cli/kubectl-stash_pause_backup.md
docs/reference/cli/kubectl-stash_resume.md
docs/reference/cli/kubectl-stash_resume_backup.md

Update docs for stashed/cli@8399b7e5

---

docs/guides/troubleshooting/how-to-troubleshooot/index.md

Add Debug Helper Command in Troubleshooting Guide

---

docs/setup/install/community.md
docs/setup/install/enterprise.md
docs/setup/install/troubleshoting.md

Add requirements in installation doc.

---

docs/README.md
docs/guides/README.md

Update Documentation Homepage

---

docs/guides/troubleshooting/how-to-troubleshoot/index.md

Add `Backup NotReady` and `Restore Pending` in the troubleshooting guide

---

docs/reference/operator/stash_backup-pvc.md
docs/reference/operator/stash_create-vs.md
docs/reference/operator/stash_restore-pvc.md
docs/reference/operator/stash_restore-vs.md
docs/reference/operator/stash_restore.md
docs/reference/operator/stash_run-backup.md
docs/reference/operator/stash_run-hook.md
docs/reference/operator/stash_update-status.md

Update docs for stashed/stash@a56bfc73

---

docs/setup/upgrade/index.md

Fix commands to upgrade CRDs.

---

docs/setup/upgrade/index.md

Add instruction for cleaning Auto-backup resources during upgrade.

---

docs/concepts/crds/backupbatch.md
docs/concepts/crds/backupconfiguration.md
docs/concepts/crds/backupsession.md
docs/concepts/crds/restorebatch.md
docs/concepts/crds/restoresession.md

Add documentation for backup and restore timeout

---

docs/reference/cli/kubectl-stash.md
docs/reference/cli/kubectl-stash_clone.md
docs/reference/cli/kubectl-stash_clone_pvc.md
docs/reference/cli/kubectl-stash_completion.md
docs/reference/cli/kubectl-stash_cp.md
docs/reference/cli/kubectl-stash_cp_backupconfig.md
docs/reference/cli/kubectl-stash_cp_repository.md
docs/reference/cli/kubectl-stash_cp_secret.md
docs/reference/cli/kubectl-stash_cp_volumesnapshot.md
docs/reference/cli/kubectl-stash_create.md
docs/reference/cli/kubectl-stash_create_backupconfig.md
docs/reference/cli/kubectl-stash_create_repository.md
docs/reference/cli/kubectl-stash_create_restoresession.md
docs/reference/cli/kubectl-stash_debug.md
docs/reference/cli/kubectl-stash_debug_backup.md
docs/reference/cli/kubectl-stash_debug_operator.md
docs/reference/cli/kubectl-stash_debug_restore.md
docs/reference/cli/kubectl-stash_delete.md
docs/reference/cli/kubectl-stash_delete_snapshot.md
docs/reference/cli/kubectl-stash_download.md
docs/reference/cli/kubectl-stash_pause.md
docs/reference/cli/kubectl-stash_pause_backup.md
docs/reference/cli/kubectl-stash_resume.md
docs/reference/cli/kubectl-stash_resume_backup.md
docs/reference/cli/kubectl-stash_trigger.md
docs/reference/cli/kubectl-stash_unlock.md
docs/reference/cli/kubectl-stash_version.md

Update docs for stashed/cli@4942f3ec

---

.github/workflows/preview-website.yml

Use Go 1.19

---

docs/CONTRIBUTING.md
docs/FAQ/README.md
docs/support.md

Remove slack links

---

.github/workflows/ci.yml
.github/workflows/preview-website.yml

Test against Kubernetes 1.25.0

---

docs/reference/cli/kubectl-stash.md
docs/reference/cli/kubectl-stash_clone.md
docs/reference/cli/kubectl-stash_clone_pvc.md
docs/reference/cli/kubectl-stash_completion.md
docs/reference/cli/kubectl-stash_cp.md
docs/reference/cli/kubectl-stash_cp_backupconfig.md
docs/reference/cli/kubectl-stash_cp_repository.md
docs/reference/cli/kubectl-stash_cp_secret.md
docs/reference/cli/kubectl-stash_cp_volumesnapshot.md
docs/reference/cli/kubectl-stash_create.md
docs/reference/cli/kubectl-stash_create_backupconfig.md
docs/reference/cli/kubectl-stash_create_repository.md
docs/reference/cli/kubectl-stash_create_restoresession.md
docs/reference/cli/kubectl-stash_debug.md
docs/reference/cli/kubectl-stash_debug_backup.md
docs/reference/cli/kubectl-stash_debug_operator.md
docs/reference/cli/kubectl-stash_debug_restore.md
docs/reference/cli/kubectl-stash_delete.md
docs/reference/cli/kubectl-stash_delete_snapshot.md
docs/reference/cli/kubectl-stash_download.md
docs/reference/cli/kubectl-stash_pause.md
docs/reference/cli/kubectl-stash_pause_backup.md
docs/reference/cli/kubectl-stash_resume.md
docs/reference/cli/kubectl-stash_resume_backup.md
docs/reference/cli/kubectl-stash_trigger.md
docs/reference/cli/kubectl-stash_unlock.md
docs/reference/cli/kubectl-stash_version.md

Update docs for stashed/cli@55cd97a6

---

.github/workflows/ci.yml
.github/workflows/preview-website.yml

Update workflows (Go 1.20, k8s 1.26)

---

docs/CHANGELOG-v2024.2.9-rc.0.md

Release: v2024.2.9-rc.0
Release-tracker: https://github.com/stashed/CHANGELOG/pull/70

Prepare for release v2024.2.9-rc.0

---

.github/workflows/preview-website.yml

Use Go 1.22

---

docs/reference/cli/kubectl-stash_check.md
docs/reference/cli/kubectl-stash_rebuild-index.md

Update docs for stashed/cli@a4dd874e

---

docs/reference/cli/kubectl-stash.md

Update docs for stashed/cli@2eb6b48d

---

docs/reference/cli/kubectl-stash.md
docs/reference/cli/kubectl-stash_delete_snapshot.md
docs/reference/cli/kubectl-stash_migrate.md
docs/reference/cli/kubectl-stash_prune.md

Update docs for stashed/cli@fad79b34

---

.github/workflows/preview-website.yml

Use Go 1.24
