stashed/docs

- docs/concepts/crds/appbinding.md
- docs/examples/crds/appbinding.yaml
Stash does not use `secretTransformations` field yet. Hence, keeping this in concepts doc may mislead the users.
> Remove `secretTransformations` part of `AppBinding` from concepts doc

- docs/CHANGELOG-v2020.07.09-beta.0.md
Release: v2020.07.09-beta.0
Release-tracker: https://github.com/stashed/CHANGELOG/pull/2
> Prepare for release v2020.07.09-beta.0

- docs/CHANGELOG-v2020.08.26-rc.0.md
Release: v2020.08.26-rc.0
Release-tracker: https://github.com/stashed/CHANGELOG/pull/4
> Prepare for release v2020.08.26-rc.0

- docs/CHANGELOG-v2020.08.26-rc.1.md
Release: v2020.08.26-rc.1
Release-tracker: https://github.com/stashed/CHANGELOG/pull/5
> Prepare for release v2020.08.26-rc.1

- docs/CHANGELOG-v2020.08.27-rc.0.md
Release: v2020.08.27-rc.0
Release-tracker: https://github.com/stashed/CHANGELOG/pull/6
> Prepare for release v2020.08.27-rc.0

- docs/CHANGELOG-v2020.08.27.md
Release: v2020.08.27
Release-tracker: https://github.com/stashed/CHANGELOG/pull/7
> Prepare for release v2020.08.27

- docs/CHANGELOG-v2020.09.16.md
Release: v2020.09.16
Release-tracker: https://github.com/stashed/CHANGELOG/pull/8
> Prepare for release v2020.09.16

- docs/CHANGELOG-v2020.09.29.md
Release: v2020.09.29
Release-tracker: https://github.com/stashed/CHANGELOG/pull/10
> Prepare for release v2020.09.29

- docs/CHANGELOG-v2020.10.21.md
Release: v2020.10.21
Release-tracker: https://github.com/stashed/CHANGELOG/pull/16
> Prepare for release v2020.10.21

- docs/CHANGELOG-v2020.10.30.md
Release: v2020.10.30
Release-tracker: https://github.com/stashed/CHANGELOG/pull/22
> Prepare for release v2020.10.30

- docs/reference/operator/stash_run-hook.md
- docs/reference/operator/stash_update-status.md
> Update docs for stashed/stash@e88ab544

- docs/CHANGELOG-v2020.11.06.md
Release: v2020.11.06
Release-tracker: https://github.com/stashed/CHANGELOG/pull/23
> Prepare for release v2020.11.06

- docs/CHANGELOG-v2020.12.17.md
Release: v2020.12.17
Release-tracker: https://github.com/stashed/CHANGELOG/pull/25
> Prepare for release v2020.12.17

- docs/CHANGELOG-v2021.01.21.md
Release: v2021.01.21
Release-tracker: https://github.com/stashed/CHANGELOG/pull/27
> Prepare for release v2021.01.21

- docs/CHANGELOG-v2021.03.08.md
- docs/examples/guides/latest/batch-backup/appbinding.yaml
- docs/examples/guides/latest/hooks/batch-backup/wordpress-mysql.yaml
- docs/examples/guides/latest/hooks/sample-mysql.yaml
- docs/guides/latest/batch-backup/batch-backup.md
- docs/guides/latest/hooks/backup-and-restore-hooks.md
- docs/guides/latest/hooks/batch-backup-hooks.md
Release: v2021.03.08
Release-tracker: https://github.com/stashed/CHANGELOG/pull/29
> Prepare for release v2021.03.08

- docs/CHANGELOG-v2021.03.11.md
- docs/examples/guides/latest/auto-backup/database/sample-postgres-1.yaml
- docs/examples/guides/latest/auto-backup/database/sample-postgres-2.yaml
Release: v2021.03.11
Release-tracker: https://github.com/stashed/CHANGELOG/pull/31
> Prepare for release v2021.03.11

- docs/CHANGELOG-v2021.03.17.md
Release: v2021.03.17
Release-tracker: https://github.com/stashed/CHANGELOG/pull/32
> Prepare for release v2021.03.17

- docs/CHANGELOG-v2021.04.07.md
Release: v2021.04.07
Release-tracker: https://github.com/stashed/CHANGELOG/pull/33
> Prepare for release v2021.04.07

- docs/CHANGELOG-v2021.04.09.md
Release: v2021.04.09
Release-tracker: https://github.com/stashed/CHANGELOG/pull/34
> Prepare for release v2021.04.09

- docs/CHANGELOG-v2021.04.12.md
Release: v2021.04.12
Release-tracker: https://github.com/stashed/CHANGELOG/pull/35
> Prepare for release v2021.04.12

- docs/CHANGELOG-v2021.6.18.md
- docs/addons/mysql/standalone/examples/restored-mysql.yaml
- docs/addons/mysql/standalone/examples/sample-mysql.yaml
- docs/addons/mysql/standalone/index.md
- docs/examples/guides/latest/batch-backup/appbinding.yaml
- docs/examples/guides/latest/hooks/batch-backup/wordpress-mysql.yaml
- docs/examples/guides/latest/hooks/sample-mysql.yaml
- docs/guides/latest/batch-backup/batch-backup.md
- docs/guides/latest/hooks/backup-and-restore-hooks.md
- docs/guides/latest/hooks/batch-backup-hooks.md
- docs/setup/upgrade/index.md
Release: v2021.6.18
Release-tracker: https://github.com/stashed/CHANGELOG/pull/37
> Prepare for release v2021.6.18

- docs/CHANGELOG-v2021.06.23.md
Release: v2021.06.23
Release-tracker: https://github.com/stashed/CHANGELOG/pull/38
> Prepare for release v2021.06.23

- .github/workflows/preview-website.yml
- docs/CHANGELOG-v2021.08.02.md
Release: v2021.08.02
Release-tracker: https://github.com/stashed/CHANGELOG/pull/39
> Prepare for release v2021.08.02

- docs/CHANGELOG-v2021.11.24.md
Release: v2021.11.24
Release-tracker: https://github.com/stashed/CHANGELOG/pull/43
> Prepare for release v2021.11.24

- docs/CHANGELOG-v2022.05.12.md
Release: v2022.05.12
Release-tracker: https://github.com/stashed/CHANGELOG/pull/47
> Prepare for release v2022.05.12

- docs/CHANGELOG-v2022.05.18.md
Release: v2022.05.18
Release-tracker: https://github.com/stashed/CHANGELOG/pull/48
> Prepare for release v2022.05.18

- docs/CHANGELOG-v2022.06.21.md
Release: v2022.06.21
Release-tracker: https://github.com/stashed/CHANGELOG/pull/49
> Prepare for release v2022.06.21

- docs/CHANGELOG-v2022.06.27.md
Release: v2022.06.27
Release-tracker: https://github.com/stashed/CHANGELOG/pull/50
> Prepare for release v2022.06.27

- docs/CHANGELOG-v2022.07.09.md
Release: v2022.07.09
Release-tracker: https://github.com/stashed/CHANGELOG/pull/53
> Prepare for release v2022.07.09

- docs/CHANGELOG-v2022.09.29.md
Release: v2022.09.29
Release-tracker: https://github.com/stashed/CHANGELOG/pull/57
> Prepare for release v2022.09.29

- docs/CHANGELOG-v2022.12.11.md
- docs/addons/elasticsearch/kubedb/index.md
- docs/guides/troubleshooting/repo-locked/index.md
- docs/guides/use-cases/exclude-include-files/index.md
Release: v2022.12.11
Release-tracker: https://github.com/stashed/CHANGELOG/pull/59
> Prepare for release v2022.12.11

- docs/CHANGELOG-v2023.01.05.md
Release: v2023.01.05
Release-tracker: https://github.com/stashed/CHANGELOG/pull/60
> Prepare for release v2023.01.05

- docs/CHANGELOG-v2023.02.28.md
Release: v2023.02.28
Release-tracker: https://github.com/stashed/CHANGELOG/pull/61
> Prepare for release v2023.02.28

- docs/CHANGELOG-v2023.03.13.md
Release: v2023.03.13
Release-tracker: https://github.com/stashed/CHANGELOG/pull/63
> Prepare for release v2023.03.13

- docs/CHANGELOG-v2023.03.20.md
Release: v2023.03.20
Release-tracker: https://github.com/stashed/CHANGELOG/pull/64
> Prepare for release v2023.03.20

- docs/CHANGELOG-v2023.04.30.md
Release: v2023.04.30
Release-tracker: https://github.com/stashed/CHANGELOG/pull/65
> Prepare for release v2023.04.30

- docs/CHANGELOG-v2023.05.31.md
Release: v2023.05.31
Release-tracker: https://github.com/stashed/CHANGELOG/pull/66
> Prepare for release v2023.05.31

- docs/CHANGELOG-v2023.08.18.md
Release: v2023.08.18
Release-tracker: https://github.com/stashed/CHANGELOG/pull/68
> Prepare for release v2023.08.14

- docs/concepts/crds/backupconfiguration/index.md
- docs/guides/hooks/overview/index.md
Signed-off-by: anisurrahman75 <sunny.cse7575@gmail.com>
> Add new hookExecutionPolicy `OnFinalRetryFailure`

- docs/CHANGELOG-v2023.10.9.md
Release: v2023.10.9
Release-tracker: https://github.com/stashed/CHANGELOG/pull/69
> Prepare for release v2023.10.9

- docs/reference/cli/kubectl-stash.md
- docs/reference/cli/kubectl-stash_gen.md
- docs/reference/cli/kubectl-stash_gen_rules.md
- docs/reference/cli/kubectl-stash_key.md
- docs/reference/cli/kubectl-stash_key_add.md
- docs/reference/cli/kubectl-stash_key_list.md
- docs/reference/cli/kubectl-stash_key_remove.md
- docs/reference/cli/kubectl-stash_key_update.md
> Update docs for stashed/cli@575a83da

- docs/CHANGELOG-v2024.2.13.md
Release: v2024.2.13
Release-tracker: https://github.com/stashed/CHANGELOG/pull/71
> Prepare for release v2024.2.13

- docs/CHANGELOG-v2024.4.8.md
Release: v2024.4.8
Release-tracker: https://github.com/stashed/CHANGELOG/pull/72
> Prepare for release v2024.4.8

- docs/CHANGELOG-v2024.8.27.md
Release: v2024.8.27
Release-tracker: https://github.com/stashed/CHANGELOG/pull/75
> Prepare for release v2024.8.27

- docs/CHANGELOG-v2024.9.30.md
Release: v2024.9.30
Release-tracker: https://github.com/stashed/CHANGELOG/pull/76
> Prepare for release v2024.9.30

- docs/CHANGELOG-v2024.12.18.md
Release: v2024.12.18
Release-tracker: https://github.com/stashed/CHANGELOG/pull/77
> Prepare for release v2024.12.18

- docs/CHANGELOG-v2025.1.9.md
Release: v2025.1.9
Release-tracker: https://github.com/stashed/CHANGELOG/pull/79
> Prepare for release v2025.1.9

- docs/CHANGELOG-v2025.2.10.md
Release: v2025.2.10
Release-tracker: https://github.com/stashed/CHANGELOG/pull/80
> Prepare for release v2025.2.10

- docs/CHANGELOG-v2025.7.31.md
Release: v2025.7.31
Release-tracker: https://github.com/stashed/CHANGELOG/pull/83
> Prepare for release v2025.7.31
